const education = {
  Codecademy: {
    duration: "2022-Present",
    certifications: [
      {
        title: "Learn React",
        topics: [
          "JSX",
          "Components and Advanced JSX",
          "Components Interacting",
          "Props",
          "Hooks",
          "React Programming Patterns",
          "React Styles",
          "React Forms",
        ],
      },
      {
        title: "Learn JavaScript Unit Testing",
        topics: [
          "Why Test?",
          "Write Good Tests With Mocha",
          "Learn Test-Driven Development With Mocha",
        ],
      },
      {
        title: "Learn Node.js",
        topics: [
          "Welcome to Learn Node.js",
          "What is Back-End?",
          "Introduction to Node.js",
          "Node.js Essentials",
          "Setting up a Server with HTTP",
          "Next Steps",
        ],
      },
      {
        title: "Learn the Command Line",
        topics: [
          "Navigating the File System",
          "Viewing and Changing the File System",
          "Redirecting Input and Output",
          "Configuring the Environment",
        ],
      },
      {
        title: "Learn Git & GitHub",
        topics: [
          "Introduction: Git & GitHub",
          "Basic Git Workflow",
          "Important Git Operations",
          "Introduction to GitHub",
          "GitHub & Markdown",
          "Git Branching",
          "Git Teamwork",
          "Deploying Websites using Git and GitHub",
          "Best Practices for GitHub Repositories",
          "Collaborating with the GitHub Community",
          "GitHub Features: Issues, CLI, & Actions",
        ],
      },
      {
        title: "Learn jQuery",
        topics: [
          "Introduction",
          "Effects",
          "Event Handlers",
          "Style Methods",
          "Traversing the DOM",
        ],
      },
      {
        title: "Learn JavaScript",
        topics: [
          "Introduction",
          "Conditionals",
          "Functions",
          "Scope",
          "Arrays",
          "Loops",
          "Iterators",
          "Objects",
        ],
      },
      {
        title: "Building Interactive JavaScript Websites",
        topics: [
          "JavaScript Interactive Websites",
          "DOM Events with JavaScript",
          "Templating with Handlebars",
        ],
      },
      {
        title: "Learn Intermediate JavaScript",
        topics: [
          "Classes",
          "Modules",
          "Promises",
          "Async-Await",
          "Requests",
          "Errors and Error Handling",
          "JavaScript Under the Hood",
          "JavaScript Best Practices",
        ],
      },
      {
        title: "Learn PHP Skill Path",
        topics: [
          "Introduction to the Learn PHP Skill Path",
          "PHP Variables, Strings, and Numbers",
          "PHP Functions",
          "PHP Conditionals and Logic",
          "PHP Arrays and Loops",
          "PHP and HTML",
          "PHP Classes and Objects",
          "Learn PHP Next Steps",
        ],
      },
      {
        title: "Learn CSS",
        topics: [
          "Syntax and Selectors",
          "Visual Rules",
          "The Box Model",
          "Display and Positioning",
          "Colors",
          "Typography",
        ],
      },
      {
        title: "Learn Intermediate CSS",
        topics: [
          "Layout with Flexbox",
          "Grid",
          "Transitions",
          "CSS Code Challenges",
          "Responsive Design",
          "Variables and Functions",
          "Accessibility",
          "Browser Compatibility",
        ],
      },
      {
        title: "Learn Navigation Design",
        topics: ["Links and Buttons", "Secondary Navigation"],
      },
      {
        title: "Learn Bootstrap",
        topics: ["Grid", "Utilities", "Components"],
      },
      {
        title: "Learn Sass",
        topics: [
          "Create a Sass Stylesheet",
          "Mixins and the & Selector",
          "Functions and Operations",
          "Sustainable SCSS",
        ],
      },
      {
        title: "Learn the Basics of Regular Expressions",
        topics: ["Introduction to Regular Expressions"],
      },
      {
        title: "Build a Website with HTML, CSS, and GitHub Pages",
        topics: [
          "Beginner HTML",
          "Beginner CSS",
          "How to Build Websites on Your Own Computer",
          "Intermediate CSS: Colors and Typography",
          "Intermediate CSS: Layout and Positioning",
          "Responsive Design and Accessibility",
          "Advanced CSS: Flexbox and CSS Transitions",
          "Finishing Touches and Publishing a Website",
          "Learn How to Build Websites Capstone Project",
        ],
      },
      {
        title: "Learn HTML",
        topics: [
          "Introduction to Web Development",
          "Elements and Structure",
          "Tables",
          "Forms",
          "Semantic HTML",
        ],
      },
      {
        title: "Learn How to Code",
        topics: [
          "Basics of Programming I",
          "Basics of Programming II",
          "Basics of Programming III",
        ],
      },
    ],
  },
  freeCodeCamp: {
    duration: "2023-Present",
    certifications: [
      {
        title: "JavaScript Algorithms and Data Structures",
        topics: [
          "Basic JavaScript",
          "ES6",
          "Regular Expressions",
          "Debugging",
          "Basic Data Structures",
          "Basic Algorithm Scripting",
          "Object Oriented Programming",
          "Intermediate Algorithm Scripting",
          "JavaScript Algorithms and Data Structures Projects",
        ],
      },
      {
        title: "Responsive Web Design",
        topics: ["HTML", "CSS"],
      },
    ],
  },
  udemy: {
    duration: "2023-Present",
    courses: [
      {
        title: "The Web Developer Bootcamp",
        topics: [
          "ReactJS",
          "Unix (Command Line) Commands",
          "JavaScript",
          "Asynchronous JavaScript",
          "AJAX and API",
          "DOM Manipulation",
          "Bootstrap 4 and 5",
          "Bulma CSS Framework",
          "HTML",
          "CSS3",
          "Flexbox",
          "Responsive Design",
        ],
      },
    ],
  },
  "ITT Technical Institute": {
    duration: "2002-2008",
    degrees: [
      {
        title:
          "Associates of Applied Science Degree in Computer Drafting and Design",
        topics: [
          "Dynamics in an Information Society",
          "Computers in Technology",
          "Problem Solving",
          "Introduction to Design and Drafting",
          "Drafting/CAD Methods",
          "College Mathematics I",
          "Architectural Drafting I",
          "Rapid Visualization",
          "College Mathematics II",
          "Engineering Graphics I",
          "Materials and Processes",
          "Physics",
          "Architectural Drafting II",
          "Descriptive Geometry",
          "Composition I",
          "Engineering Graphics II",
          "Digital Information Management",
          "Composition II",
          "Civil Drafting and Introduction to GIS",
          "Basic Design Theory and Methods",
          "Physical and Computer-Aided 3D Modeling",
          "Design and Drafting Capstone Project",
          "Economic Problems",
          "Professional Procedures and Portfolio",
        ],
      },
      {
        title:
          "Bachelor of Science Degree in Digital Entertainment and Game Design",
        topics: [
          "Introduction to Computer Programming",
          "Animation I",
          "Audio/Video Techniques",
          "Introduction to Gaming Technology",
          "Managing Game Development",
          "Research Methods",
          "Physics of Animation",
          "Game Design Process",
          "Game Design Strategies",
          "Advanced Animation",
          "Written Analysis",
          "Game Interface Design",
          "Level Design I",
          "Creative Writing and Storyboarding",
          "Game Engines and Production",
          "The Game Development Team",
          "Ethics",
          "Environmental Issues",
          "Level Design II",
          "Statistics",
          "Economics and Change",
          "Capstone Project",
          "Modern and Contemporary Art",
          "Contemporary World Culture",
        ],
      },
    ],
  },
};

export default education;
